name: "Build and Push Docker Images"

# Usage - copy into project .github/workflows/build-and-push-docker-image.yaml
#on:
#  release:
#    types: [published]
#  pull_request:
#    branches: ["main"]  <-- customize to your own repo's default branch
#
#jobs:
#  push_to_registry:
#    name: Build
#    uses: waggle-sensor/.github/.github/workflows/build-and-push-docker-image.yml@main
#    secrets: inherit
#    with:
#      platforms: "linux/amd64,linux/arm64"       <-- optional, to override default below
#      context: .                                 <-- optional, to override default below
#      image: ${{ github.event.repository.name }} <-- optional, to override default below

on:
  workflow_call:
    inputs:
      platforms:
        required: false
        type: string
        default: "linux/amd64,linux/arm64"
      context:
        required: false
        type: string
        default: .
      image:
        required: false
        type: string
        default: ${{ github.event.repository.name }}

jobs:
  push_to_registry:
    name: Build and Push Docker Images
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU for multi-arch builds
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker buildx for multi-arch builds
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKER_ORG }}/${{ inputs.image }}
          tags: |
            type=ref,event=pr
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.context }}
          platforms: ${{ inputs.platforms }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
